<?php

return [

	/**
	 * Generated request classes will be store in specified directory.
	 *
	 * Change this property when you want to store classes generated by php artisan make:rb_request YourRequestName
	 * in different directory.
	 */
	'request_path' =>  base_path( 'app/Http/Requests/' ),

	/**
	 * Parent Request Namespace is a namespace of the class that will be extended for generated request class.
	 *
	 * Change this property when you want classes generated by "php artisan make:rb_request YourRequestName" command
	 * extend from your custom class and not from RB\Requests\RB_Request
	 */
	'parent_request_namespace' => 'RB\Requests\RB_Request',

	/**
	 * Namespace for generated request class.
	 *
	 * Change this property when you want classes generated by "php artisan make:rb_request YourRequestName" command
	 * have different than App\Http\Requests namespace.
	 * E.g. you changed request_path and you want namespace to be changed too.
	 */
	'request_namespace' => 'App\Http\Requests',

	/**
	 * Default messages
	 */
	'messages' => [
		'failed_validation' => 'The given data was invalid.',
	]
];
